### ISSUE TITLE
Having issue when running colcon build --symlink-install on pop os

### ISSUE THREAD

**Issue by M-Usamah** [ros2/examples#370]
Finished <<< test_osrf_testing_tools_cpp [0.36s]                                                          
--- stderr: ament_package
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_package [1.64s]
--- stderr: ament_pycodestyle                                                                             
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_pycodestyle [1.52s]
--- stderr: osrf_pycommon
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< osrf_pycommon [1.61s]
--- stderr: ament_lint
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_lint [1.72s]
Starting >>> ament_cmake_core
Starting >>> ament_flake8
Starting >>> ament_pyflakes                                                                      
--- stderr: ament_cppcheck
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_cppcheck [1.78s]
Finished <<< ament_cmake_core [0.48s]                                                                   
Starting >>> ament_cmake_libraries
Starting >>> ament_cmake_export_libraries
Starting >>> ament_cmake_python
Starting >>> ament_cmake_include_directories
Starting >>> ament_cmake_export_definitions                                                 
Starting >>> ament_cmake_export_include_directories
Starting >>> ament_cmake_export_link_flags
Starting >>> ament_cmake_version                                                             
Starting >>> test_interface_files
Starting >>> ros_environment
Finished <<< iceoryx_posh [1.14s]                                                            
Starting >>> iceoryx_binding_c
Starting >>> iceoryx_introspection
Finished <<< ament_cmake_libraries [0.68s]                                             
Finished <<< ament_cmake_export_libraries [0.69s]
Starting >>> ament_cmake_export_dependencies
Starting >>> ament_cmake_export_targets
Starting >>> ament_cmake_export_interfaces
--- stderr: ament_flake8                                                               
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_flake8 [1.26s]
--- stderr: ament_pyflakes
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_pyflakes [1.28s]
Finished <<< ament_cmake_python [0.83s]                                      
Starting >>> ament_cmake_test
Starting >>> ament_pep257
Starting >>> ament_mypy
Finished <<< ament_cmake_export_definitions [0.88s]
Finished <<< ament_cmake_include_directories [0.92s]                                      
Finished <<< ament_cmake_export_link_flags [0.86s]
Finished <<< ament_cmake_export_include_directories [0.94s]
Finished <<< ament_cmake_version [0.90s]
Finished <<< test_interface_files [0.91s]                                      
Starting >>> ament_cmake_target_dependencies
Finished <<< ros_environment [0.94s]
Finished <<< iceoryx_introspection [1.25s]                                 
Finished <<< iceoryx_binding_c [1.33s]                                     
Starting >>> cyclonedds
Finished <<< ament_cmake_export_interfaces [1.05s]                                       
Finished <<< ament_cmake_export_dependencies [1.11s]
Finished <<< ament_cmake_export_targets [1.13s]                                     
Finished <<< ament_cmake_test [1.05s]
Starting >>> ament_cmake_gtest
Starting >>> ament_cmake_pytest
Starting >>> ament_lint_auto
Starting >>> ament_cmake_google_benchmark                                         
Starting >>> ament_cmake_nose
Starting >>> ament_cmake_vendor_package
Finished <<< ament_cmake_target_dependencies [0.96s]
Finished <<< cyclonedds [0.60s]                                                                               
--- stderr: ament_mypy                                                            
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_mypy [1.43s]
--- stderr: ament_pep257                                                                         
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ament_pep257 [1.49s]
Starting >>> ament_copyright
Finished <<< ament_cmake_gtest [0.53s]
Finished <<< ament_cmake_pytest [0.54s]                                                                      
Starting >>> ament_cmake_gen_version_h
Starting >>> ament_cmake_gmock
Finished <<< ament_lint_auto [0.60s]
Finished <<< ament_cmake_nose [0.60s]                                               
[8.397s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'powershell': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/hook'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 425, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_powershell/shell/powershell.py", line 148, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 49, in expand_template
    os.makedirs(str(destination_path.parent), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/hook'

[8.398s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/hook'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 425, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 75, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 49, in expand_template
    os.makedirs(str(destination_path.parent), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/hook'

[8.398s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/hook'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 425, in create_environment_hook
    hook = extension.create_hook_prepend_value(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 127, in create_hook_prepend_value
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 49, in expand_template
    os.makedirs(str(destination_path.parent), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/hook'

[8.398s] ERROR:colcon.colcon_core.environment:Exception in environment extension 'cmake_prefix_path': Could not find a primary shell extension for creating an environment hook
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 191, in create_environment_hooks
    hooks = extension.create_environment_hooks(prefix_path, pkg_name)
  File "/usr/lib/python3/dist-packages/colcon_cmake/environment/cmake_prefix_path.py", line 28, in create_environment_hooks
    hooks += create_environment_hook(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 444, in create_environment_hook
    raise RuntimeError(
RuntimeError: Could not find a primary shell extension for creating an environment hook

[8.406s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'powershell': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.ps1'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 139, in create_environment_scripts_only
    scripts = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_powershell/shell/powershell.py", line 117, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.ps1'

[8.406s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'dsv': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.dsv'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 139, in create_environment_scripts_only
    scripts = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/dsv.py", line 30, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 53, in expand_template
    destination_path.unlink()
  File "/usr/lib/python3.10/pathlib.py", line 1206, in unlink
    self._accessor.unlink(self)
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.dsv'

[8.406s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'sh': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.sh'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 139, in create_environment_scripts_only
    scripts = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 83, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.sh'

[8.406s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'bash': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.bash'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 139, in create_environment_scripts_only
    scripts = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_bash/shell/bash.py", line 63, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.bash'

[8.407s] ERROR:colcon.colcon_core.environment:Exception in shell extension 'zsh': [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.zsh'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 139, in create_environment_scripts_only
    scripts = extension.create_package_script(
  File "/usr/lib/python3/dist-packages/colcon_zsh/shell/zsh.py", line 63, in create_package_script
    expand_template(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/template/__init__.py", line 54, in expand_template
    with destination_path.open('w') as h:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/ament_cmake_google_benchmark/package.zsh'

--- stderr: ament_cmake_google_benchmark
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:5 (file):
  file failed to open for writing (Permission denied):

    /home/usamah/ros2_humble/build/ament_cmake_google_benchmark/symlink_install_manifest.txt
Call Stack (most recent call first):
  cmake_install.cmake:41 (include)

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/colcon-core/packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 84, in build
    create_environment_scripts(
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 89, in create_environment_scripts
    create_file_with_runtime_dependencies(prefix_path, pkg))
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 171, in create_file_with_runtime_dependencies
    path.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/colcon-core'
---
Failed   <<< ament_cmake_google_benchmark [0.84s, exited with code 1]
Aborted  <<< ament_cmake_vendor_package [0.81s]
Aborted  <<< ament_cmake_gen_version_h [0.32s]
Aborted  <<< ament_cmake_gmock [0.37s]                                                                     
Aborted  <<< ament_copyright [0.59s]                        

Summary: 41 packages finished [8.41s]
  1 package failed: ament_cmake_google_benchmark
  4 packages aborted: ament_cmake_gen_version_h ament_cmake_gmock ament_cmake_vendor_package ament_copyright
  10 packages had stderr output: ament_cmake_google_benchmark ament_cppcheck ament_flake8 ament_lint ament_mypy ament_package ament_pep257 ament_pycodestyle ament_pyflakes osrf_pycommon
  299 packages not processed
[Errno 13] Permission denied: '/home/usamah/ros2_humble/install/ament_cmake_google_benchmark/share/colcon-core'

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
